todolist/photolist/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static

app_name = 'photolist'  # URL Reverse에서 namespace역할을 함

urlpatterns = [
    path('new/', views.post_new, name='post_new'),
    path('', views.photo_list, name='photo_list'),
    path('<int:pk>', views.photo_detail, name='photo_detail'),
    # path('', views.home, name='home'),
    path('account/', views.account, name='account'),

]

todolist/todolist/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(
        pattern_name = 'photolist:photo_list' 
    ), name='root'),    # url이 빈공간일 때 photolist앱에서 url name인 photo_list로 /photolist 로 감
    path('admin/', admin.site.urls),
    path('photolist/', include('photolist.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    # static 위치를 알려줌

todolist/photolist/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MinLengthValidator
from django.urls import reverse

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    is_public = models.BooleanField(default=False, verbose_name='공개여부')
    photo = models.ImageField(blank=True, upload_to='photolist/post/%Y/%m/%d')
    title = models.CharField(max_length=20)
    content = models.TextField(
        validators=[MinLengthValidator(10)]
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def get_absolute_url(self):
        return reverse('photolist:photo_detail', args=[self.pk])

todolist/photolist/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
        #fields = ['photo', 'title', 'content']

todolist/photolist/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import PostForm
from .models import Post
from django.views.generic import DetailView

# def photo_list(request):
#     return render(request, 'photolist/photo_list.html')

def photo_list(request): 
    qs = Post.objects.all()
    q = request.GET.get('q', '')
    if q:
        qs = qs.filter(title__icontains=q)
    # instagram/templates/instagram/post_list.html
    return render(request, 'photolist/photo_list.html', {
        'photo_list': qs,
        'q': q ,
    })

class PostDetailView(DetailView):
    template_name = 'photolist/photo_detail.html'
    model = Post
    # queryset = Post.objects.filter(is_public=True)

    def get_queryset(self):
        qs = super().get_queryset()
        if not self.request.user.is_authenticated:
            qs = qs.filter(is_public=True)
        return qs

photo_detail = PostDetailView.as_view()

def home(request):
    return render(request, 'photolist/home.html')

def account(request):
    return render(request, 'photolist/account.html')


#def post_new(request):
    # if request.method == 'POST':
    #     form = PostForm(request.POST, request.FILES)
    #     if form.is_valid():
    #         post = form.save(commit=False)
    #         post.save()
    #         messages.success(request, '포스팅을 저장했습니다.')
    #         return redirect(post)
    #     else:
    #         form = PostForm()

    #     return render(request, 'photolist/post_form.html', {
    #         'form': form,
    #         'post': None
    #     })
    #form = PostForm()
    #return render(request, 'photolist/post_form.html', {
    #    'form': form
    #})

def post_new(request):
    if request.method == 'POST' or request.method == 'FILES':
        # 입력 내용을 DB에 저장
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            # 저장하라
            form.save()
            messages.success(request, "정상적으로 포스팅 되었습니다.")
            return redirect('photolist:photo_list')
    else:
        # 입력을 받을 수 있는 html을 갖다주기
        form = PostForm() #객체 만들어주기
    return render(request, 'photolist/post_form.html', {
        'form': form,
        })

todolist/photolist/templates/photolist/account.html
{% extends "photolist/layout.html" %}

{% block title %}
    account
{% endblock title %}

{% block content %}

<h1>Hello</h1>
<a href="https://map.kakao.com/?urlX=658075&urlY=1212822&urlLevel=3&map_type=TYPE_MAP&map_hybrid=false" target="_blank"><img width="504" height="310" src="https://map2.daum.net/map/mapservice?FORMAT=PNG&SCALE=2.5&MX=658075&MY=1212822&S=0&IW=504&IH=310&LANG=0&COORDSTM=WCONGNAMUL&logo=kakao_logo" style="border:1px solid #ccc"></a><div class="hide" style="overflow:hidden;padding:7px 11px;border:1px solid #dfdfdf;border-color:rgba(0,0,0,.1);border-radius:0 0 2px 2px;background-color:#f9f9f9;width:482px;"><strong style="float: left;"><img src="//t1.daumcdn.net/localimg/localimages/07/2018/pc/common/logo_kakaomap.png" width="72" height="16" alt="카카오맵"></strong><div style="float: right;position:relative"><a style="font-size:12px;text-decoration:none;float:left;height:15px;padding-top:1px;line-height:15px;color:#000" target="_blank" href="https://map.kakao.com/?urlX=658075&urlY=1212822&urlLevel=3&map_type=TYPE_MAP&map_hybrid=false">지도 크게 보기</a></div></div>
<hr>
<!-- * 카카오맵 - 지도퍼가기 -->
<!-- 1. 지도 노드 -->
<div id="daumRoughmapContainer1660551230526" class="root_daum_roughmap root_daum_roughmap_landing"></div>

<!--
	2. 설치 스크립트
	* 지도 퍼가기 서비스를 2개 이상 넣을 경우, 설치 스크립트는 하나만 삽입합니다.
-->
<script charset="UTF-8" class="daum_roughmap_loader_script" src="https://ssl.daumcdn.net/dmaps/map_js_init/roughmapLoader.js"></script>

<!-- 3. 실행 스크립트 -->
<script charset="UTF-8">
	new daum.roughmap.Lander({
		"timestamp" : "1660551230526",
		"key" : "2bdf4",
		"mapWidth" : "200",
		"mapHeight" : "360"
	}).render();
</script>
{% endblock content %}

todolist/photolist/templates/photolist/layout.html
{% extends "layout.html" %}

todolist/photolist/templates/photolist/photo_detail.html
{% extends "photolist/layout.html" %}
{% load static %}
{% load bootstrap4 %}

{% block title %}
  photo_detail
{% endblock title %}

{% block head %}
    <link rel="stylesheet" href="{% static "css/instagram.css" %}">
{% endblock head %}


{% block content %}
    <!-- instagram-content -->
    <div class="instagram-card">
        <div class="instagram-card-header">
            <img src="{% static "images/photo.jpg" %}" class="instagram-card-user-image"/>
            <a class="instagram-card-user-name" href="#">followmeto</a>
            <div class="instagram-card-time">58 min</div>
        </div>
    
        <div class="intagram-card-image">
            <img src="{% static "images/photo.jpg" %}" height="600px"/>
        </div>
    
        <div class="instagram-card-content">
            <p class="likes">18.068 Me gusta</p>
            <p>
                <!-- 사용자 이름 -->
                <a class="instagram-card-content-user" href="#">followmeto</a>
                <!-- 사용자 이름 --> 
                <!-- 사용자 내용 입력 -->
                So excited to have made it to Lapland! Our first stop was sleeping inside a room made 
                entirely of ice at the Kemi Snow Hotel 😱 Stoked that I've ticked this off my bucket list 
                and never have to do it again... Let's just say the novelty of sleeping in -5 degrees 
                temperature quickly wears off (but hey, it was a COOL experience nonetheless) 😜❄️ 
                <!-- 사용자 내용 입력 -->
                <a class="hashtag" href="#">#visitkemi</a>
            </p>
            <!-- 답변수 -->
            <p class="comments">ver los 48 comentarios</p>
            <!-- 답변수 -->
            <!-- 다른 사용자 댓글 -->
            <br><a class="user-comment" href="#">sanguine.j@loaf_made</a> wowwwwww</br>
            <br><a class="user-comment" href="#">spainstakeoverWow</a> 😍</br>
            <br><a class="user-comment" href="#">edieandottotravelsSo</a> cool ❄️</br>
            <hr>
            <!-- 다른 사용자 댓글 -->
        </div>
        
        <!-- 댓글 입력칸 -->
        <div class="instagram-card-footer">
            <a class="footer-action-icons" href="#"><i class="fa fa-heart-o"></i></a><!-- 하트 이미지 -->
            <input class="comments-input" type="text" placeholder="댓글 입력..."/>
            {% comment %} <a class="footer-action-icons" href="#"><i class="fa fa-ellipsis-h"></i></a> {% endcomment %}
        </div>
         <!-- 댓글 입력칸 -->
    </div>
    <!-- instagram-content -->
{% endblock content %}

todolist/photolist/templates/photolist/photo_list.html
{% extends "photolist/layout.html" %}
{% load static %}

{% block title %}
  photolist
{% endblock title %}

{% block content %}
    <!-- header -->
    <header id="header">
        <div class="header_container">
            <!-- info -->
            <div id="info">         
                <img class="gomduli_cheeze" src="{% static "images/gomduli_cheeze.jpg" %}">
                <div class="info">
                    <h4 class="info_header">강원대학교 근처 맛집 <br>강맛</h4>
                    <p class="info_content">곰두리들도 인정할 만한 당신만의 맛집들을 기록하세요.</p>
                </div>
            </div>
            <!-- login -->
            <div class="login">
                <h2 class="blind">로그인</h2>
                <p class="login_msg">이 사이트를 더 안전하고 편리하게 이용하세요</p>
                <a href="#" class="link_login">
                    <i class="ico_naver">
                        <span class="blind">강맛</span>
                    </i>
                    로그인
                </a>
                <div class="sub_area">
                    <div class="look_box">
                        <a href="#" class="look_id">아이디</a>
                        <a href="#" class="look_pw">비밀번호찾기</a>
                    </div>
                    <a href="#" class="member_join">
                        회원가입
                    </a>
                </div>
            </div>
        </div>
    </header>        
    <!-- header -->

    <!-- header -->
    <header id="top_container">
        <div class="top_content">
            <img class="gom_left" src="{% static "images/gomduli_left.jpg" %}">        
            <p class="top_food">강원대학교 근처 맛집 top 3!!!</p>
            <img class="gom_right" src="{% static "images/gomduli_right.jpg" %}">        
        </div>
    </header>
    <!-- header -->
    
    <!-- best_container -->

    <!-- 여기에 맛집 top3을 넣어야 합니다. -->

    <!-- best_container -->
    <div class="upload"><p class="new"><a href="{% url "photolist:post_new" %}">New</a></p></div>
    
    <a href="{% url 'photolist:post_new' %}">New22</a>

    <!-- main_container -->
    <div id="main">
        {% for post in photo_list %}
        <div class="mainBox">
            {% if post.photo %}
                <img class="memo_photo" width="450" src="{{ post.photo.url }}"/>
            {% else %}
                No Photo
            {% endif %}
            <div class="memoBox">
                <h3 class="bo">burger</h3>
                <p class="bo">haha</p>
                <div class="view-photo">
                    <a href="{{ post.get_absolute_url }} ">
                        {{ post.title }}
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <!-- main_container -->

    <script src="https://kit.fontawesome.com/54ae93b2e8.js" crossorigin="anonymous"></script>
    <script src="{% static "js/photo_board.js" %}" defer></script>
{% endblock content %}

{% block footer %}

    <footer>
        <div id="footer_box">
            <div id="footer_info">
                <div class="footer_title">
                    
                    <h2 class="circle_right">강맛</h2><br>        
                    <p>@ Kangwon National University<br>@ Team KM.Company<br>@ Project 강맛</p>
                </div>
                <div class="front_end_info">
                    <h2>front end</h2><br>
                    <p>안재진<br>김지민</p><br>
                    <h2>tech skills</h2><br>
                    <p>HTML,CSS,JavaScript</p>
                </div>
                <div class="backend_info">
                    <h2>backend</h2><br>
                    <p>한주영<br>박서희</p><br>
                    <h2>tech skills</h2><br>
                    <p>Django</p>
                </div>
                <div class="other_info">
                    <h2>Contact Us</h2><br>
                    <p>
                        <b>Email</b> annjae4676@naver.com<br><b>GitHub </b><a href="{% static 'github.com/acs0209/hackathonProject' %}"><i class="fa-brands fa-github"></i></a>
                        <br><b>facebook </b><i class="fa-brands fa-facebook"></i><br><b>instagram </b><i class="fa-brands fa-instagram"></i>
                        <br><b>twitter </b><i class="fa-brands fa-twitter"></i>
                    </p>
                </div>
            </div>

            <div class="copyright">
                <p>Copyright @ team A All rights reserved.</p>
            </div>
        </div> 
    </footer>

{% endblock footer %}

todolist/photolist/templates/photolist/post_create.html
<h1>새로운 글 작성하기</h1>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <!-- views.py에서 render()의 세번째 인자로 넘겨준 데이터는 html 내에서 에 감싸진 채로 표현될 수 있습니다. -->
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="새 글 생성하기">
</form>

todolist/photolist/templates/photolist/post_form.html
{% extends "photolist/layout.html" %}
{% load bootstrap4 %}
{% block title %}
    new
{% endblock title %}
{% block content %}
    <!-- Post Detail pk#{{ post.pk }} -->
    <div class="container">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    {% buttons %}
                        <button class="btn btn-primary">
                            저장
                        </button>
                    {% endbuttons %}
                </form>
            </div>
        </div>
    </div> 
    
    {% comment %} <div class="container">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                {% include "_form.html" %}
            </div>
        </div>
    </div> {% endcomment %}
{% endblock content%}

todolist/todolist/templates/_form.html
{% load bootstrap4 %}

<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <buttons type="submit" class="btn btn-primary">
            {{ submit_label|default:"Submit" }}
        </buttons>
    {% endbuttons %}
</form> 

todolist/todolist/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html>

    <head>
        <title>{% block title %}{% endblock title %}</title>
        <meta charset="utf-8">
        <!-- <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'bootstrap/css/styles.css' %}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet"> -->
        <link rel="stylesheet" href="{% static 'bootstrap-4.6.2-dist/css/bootstrap.min.css' %}" />
        <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'bootstrap-4.6.2-dist/js/bootstrap.min.js' %}"></script>
        <link rel="stylesheet" href="{% static "css/photo_board.css" %}">
        {% block head %}
        {% endblock head %}
    </head>

    <body>
    <!-- navbar -->
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-normal">강맛</h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="#">Profile</a>
      </nav>
      <a class="btn btn-outline-primary" href="#">Sign up</a>
    </div>
    <!-- navbar -->

    {% block content %}
    {% endblock content %}
    <hr/>


    <!-- Footer -->
    <div>
        &copy; LikelionHackaton.강원대학교
    </div>

    </body>
</html>